# code/deployment/api/Dockerfile
FROM python:3.11-slim

# Create envirment variables for OpenMP (libomp)
ENV CC=/usr/bin/clang
ENV CXX=/usr/bin/clang++
ENV CPPFLAGS="-Xpreprocessor -fopenmp"
ENV CFLAGS="-I/usr/local/opt/libomp/include"
ENV CXXFLAGS="-I/usr/local/opt/libomp/include"
ENV LDFLAGS="-Wl,-rpath,/usr/local/opt/libomp/lib -L/usr/local/opt/libomp/lib -lomp"
ENV DYLD_LIBRARY_PATH=/usr/local/opt/libomp/lib

#  main.py 
WORKDIR /app/code/deployment/api

#  requirements 
COPY code/deployment/api/requirements.txt /app/code/deployment/api/requirements.txt
RUN pip install -r /app/code/deployment/api/requirements.txt

# put repo to /app 
COPY . /app


#  uvicorn 
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
