version: '3.8'
services:
  api:
    build:
      context: ../..                         # КОНТЕКСТ = корень репо (PMLDL-Assignment-1)
      dockerfile: code/deployment/api/Dockerfile
    ports:
      - "8000:8000"
    # НЕ надо никаких volumes, если печёте модель в образ.
    # Если хотите подменять модель без пересборки — см. примечание ниже.

  app:
    build: ./app
    ports:
      - "8501:8501"
    depends_on:
      - api
